name: CI

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read
  issues: write
  checks: write
  pull-requests: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/checkout@v3
      - name: make application.yml
        run: |
          # create directory
          mkdir -p ./src/main/resources
          
          # create application.yml
          cd ./src/main/resources
          
          # application.yml 파일 생성
          touch ./application.yml
          touch ./application-server.yml
          touch ./application-test.yml
          
          # github actions 에서 설정한 값을 쓰기
          echo "${{ secrets.APPLICATION }}" >> ./application.yml
          echo "${{ secrets.APPLICATION_SERVER }}" >> ./application-server.yml
          echo "${{ secrets.APPLICATION_TEST }}" >> ./application-test.yml
        shell: bash
      - name: Build with Gradle
        run: |
          ./gradlew build
      - name: docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPO }}/ybe_mini_project .
          docker push ${{ secrets.DOCKER_REPO }}/ybe_mini_project